name: Deploy

on:
  workflow_dispatch:
  
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  deploy:
    name: Deploy Vaultwarden to Heroku
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: bash deploy.sh "$HEROKU_APP_NAME"
